//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EuCA.Pdf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EuCA.Pdf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        internal static string CULTURE_EN_US {
            get {
                return ResourceManager.GetString("CULTURE_EN_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MMM/yy.
        /// </summary>
        internal static string DATE_FORMAT {
            get {
                return ResourceManager.GetString("DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engine.
        /// </summary>
        internal static string ENGINE {
            get {
                return ResourceManager.GetString("ENGINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOfgndukBSTvnrSm1vqtidvqs8v1nun3+hrtdpm6v9uhWabCnrWfWZekzdrgpePzCOmMQ5ekscu7qOno9h3Ip93zsQ/grdzBs9yvaK+zw9uwbZmkBxDxrODz/+ihb5mkwOmMQ5ekscu7rODr/wzzrunpz+K3mrDF5v/ksqu6/gKqn6jUAeLlabjBzueurODr/wzzrunpz7iJdabw+g7kp+rpz7iJdePt9BDtrNzCnrWfWZekzRfonNzyBBDInbXH4fHQarDVxt6xcqnAwBfonNzyBBDInbWRm8ufWZfA/RTinuX39hC9dabw+g7kp+rp9umMQ5ekscu7muPwACK9RoGkscufWZeksQ==.
        /// </summary>
        internal static string EO_PDF_LICENSE {
            get {
                return ResourceManager.GetString("EO_PDF_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No technical data.
        /// </summary>
        internal static string EXPORT_CLASSIFICATION_DEFAULT {
            get {
                return ResourceManager.GetString("EXPORT_CLASSIFICATION_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECL is N/A.
        /// </summary>
        internal static string EXPORT_CONTROL_DEFAULT {
            get {
                return ResourceManager.GetString("EXPORT_CONTROL_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family:Arial; background-color:#ffffff; color:black; text-align:left; margin-top:5mm; border-top: 1px solid black&quot;&gt;&lt;div style=&quot;display:table; width:100%; margin-top:1mm;&quot;&gt;&lt;div style=&quot;display:table-row;&quot;&gt;&lt;div style=&quot;display:table-cell; font-size:14px;&quot;&gt;Export Classification: {0}; {1}&lt;/div&gt;&lt;div style=&quot;display:table-cell; text-align:right; font-size:14px;&quot;&gt;Page {3}&lt;/div&gt;&lt;/div&gt;&lt;/div&gt;&lt;div style=&quot;text-align:center; font-size:14px; margin-top:1mm;&quot;&gt;Printed on {2} P&amp;WC Proprietary – subject to rest [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FOOTER {
            get {
                return ResourceManager.GetString("FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;font-family:Arial; background-color:#ffffff; margin-top:5mm; margin-left:0mm; margin-right:0mm; border-bottom: 1px solid black;&quot;&gt;&lt;div style=&quot;display:table; width: 100%; margin-bottom:1mm&quot;&gt;&lt;div style=&quot;display:table-row;&quot;&gt;&lt;div style=&quot;display:table-cell; font-size:14px;&quot;&gt;{0}&lt;/div&gt;&lt;div style=&quot;display:table-cell; font-size:14px; text-align:right;&quot;&gt;{1}&lt;/div&gt;&lt;/div&gt;&lt;div style=&quot;display:table-row;&quot;&gt;&lt;div style=&quot;display:table-cell; font-size:14px; padding-top:1mm;&quot;&gt;{2}&lt;/div&gt;&lt;div style=&quot;display:table-cell; f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manualPn.
        /// </summary>
        internal static string MANUALPN {
            get {
                return ResourceManager.GetString("MANUALPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manualTitle.
        /// </summary>
        internal static string MANUALTITLE {
            get {
                return ResourceManager.GetString("MANUALTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {page_number}.
        /// </summary>
        internal static string PAGE_NUMBER {
            get {
                return ResourceManager.GetString("PAGE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pointRev.
        /// </summary>
        internal static string POINTREV {
            get {
                return ResourceManager.GetString("POINTREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pwcbannerinfo.
        /// </summary>
        internal static string PWCBANNERINFO {
            get {
                return ResourceManager.GetString("PWCBANNERINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyyMMdd.
        /// </summary>
        internal static string RAW_DATE_FORMAT {
            get {
                return ResourceManager.GetString("RAW_DATE_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revDate.
        /// </summary>
        internal static string REVDATE {
            get {
                return ResourceManager.GetString("REVDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revision.
        /// </summary>
        internal static string REVISION {
            get {
                return ResourceManager.GetString("REVISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body.
        /// </summary>
        internal static string TAG_BODY {
            get {
                return ResourceManager.GetString("TAG_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div.
        /// </summary>
        internal static string TAG_DIV {
            get {
                return ResourceManager.GetString("TAG_DIV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        internal static string TAG_ID {
            get {
                return ResourceManager.GetString("TAG_ID", resourceCulture);
            }
        }
    }
}
